### ISSUE TITLE
Removing Signalling server dependency

### ISSUE THREAD

**Issue by nicopace** [scottmtp/pouch-replicate-webrtc#1]
The usecase is, Would like to allow users to exchange signalling information by other means (SMS, QR code, ZeroConf/mDNS/Bonjour).

Here there is an example of webrtc without signalling server: https://github.com/cjb/serverless-webrtc

**Comment by scottmtp** [comment]
Yes, this would be helpful. Here is an example of webrtc signaling using qrcodes: https://github.com/luser/webrtc-qr-signaling

**Comment by nicopace** [comment]
Is it possible?
For what I saw, it would be needed to change code in this project, and in the replication-common project too.

**Comment by scottmtp** [comment]
Yes, I initially included rtc-quickconnect for convenience sake. However I agree that it would probably make sense to remove the signaler dependency so that any signaller or client library could be used, including qrcodes or the copy/paste method in serverless-webrtc.

**Comment by nicopace** [comment]
Great!
Will be waiting for it... please let me know if I can help you with anything to have this done.
Thanks!

**Comment by scottmtp** [comment]
This is fixed in v0.0.9. The replicator now simply accepts a datachannel and can be used with any type of webrtc signaling.

**Comment by nicopace** [comment]
Great news @scottmtp , thanks!
