### ISSUE TITLE
Make it work in the browser

### ISSUE THREAD

**Issue by nicopace** [scottmtp/pouch-replicate-webrtc#2]
Is it possible?
I believe that it would need to be implemented using browserify.

**Comment by scottmtp** [comment]
Yes, it works in the browser. The dist/ directory contains a browserified bundle that can be loaded via a script tag. I've been testing it with the 'kanban' app and can successfully replicate data between Chrome and Firefox.

Clearly the documentation can be improved to show how to integrate things.

**Comment by nicopace** [comment]
If you share the build command with me, i can document it and send you a pull request.

**Comment by scottmtp** [comment]
The script is in the package.json and browserify bundle can be updated simply by running "npm run browserify".

**Comment by scottmtp** [comment]
Also there is a bower package, so one can also "bower install pouch-replicate-webrtc --save" to install it.

**Comment by nicopace** [comment]
Do you have your browser test arround? I couldn't find it in the repo and, as we don't have require in the browser as we have on NodeJS, I don't know how to import the library in Clientside code to show a simple example in the docs.
